[package]
name = "tw-feed"
version = "0.1.0"
authors = ["Joshua Hawxwell <m@hawx.me>"]

[dependencies]
rustc-serialize = "0.3"
docopt = "0.6"
hyper = "*"
iron = "*"
oauth-client = "0.1"
horrorshow = "0.5"
time = "0.1"
